language: php

services:
    - docker

matrix:
    fast_finish: true
    include:
        - php: 7.3
          env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.3
          env: LARAVEL='6.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'

sudo: false

before_install:
    - travis_retry composer self-update
    - travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}"
    - sudo service mysql stop
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php tests/wait.php

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

script:
    - vendor/bin/phpunit

after_script:
    - docker-compose -f ./tests/docker-compose.yml down
